# coding: utf-8
from sqlalchemy import Boolean, CHAR, Column, DateTime, Index, Integer, String, Table, Unicode, text
from sqlalchemy.dialects.mssql import DATETIME2, DATETIMEOFFSET, UNIQUEIDENTIFIER
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()
metadata = Base.metadata


t_FACT_CT_DHIS2 = Table(
    'FACT_CT_DHIS2', metadata,
    Column('id', CHAR(36, 'Latin1_General_CI_AS'), nullable=False, unique=True),
    Column('DHISOrgId', Unicode(255), index=True),
    Column('SiteCode', Unicode(255), index=True),
    Column('FacilityName', Unicode(255), index=True),
    Column('County', Unicode(255), index=True),
    Column('SubCounty', Unicode(255), index=True),
    Column('Ward', Unicode(255), index=True),
    Column('ReportMonth_Year', Unicode(255), index=True),
    Column('Enrolled_Total', Integer),
    Column('StartedART_Total', Integer),
    Column('CurrentOnART_Total', Integer),
    Column('CTX_Total', Integer),
    Column('OnART_12Months', Integer),
    Column('NetCohort_12Months', Integer),
    Column('VLSuppression_12Months', Integer),
    Column('VLResultAvail_12Months', Integer),
    Column('createdAt', DATETIMEOFFSET, nullable=False),
    Column('updatedAt', DATETIMEOFFSET, nullable=False),
    Column('Start_ART_Under_1', Integer),
    Column('Start_ART_1_9', Integer),
    Column('Start_ART_10_14_M', Integer),
    Column('Start_ART_10_14_F', Integer),
    Column('Start_ART_15_19_M', Integer),
    Column('Start_ART_15_19_F', Integer),
    Column('Start_ART_20_24_M', Integer),
    Column('Start_ART_20_24_F', Integer),
    Column('Start_ART_25_Plus_M', Integer),
    Column('Start_ART_25_Plus_F', Integer),
    Column('On_ART_Under_1', Integer),
    Column('On_ART_1_9', Integer),
    Column('On_ART_10_14_M', Integer),
    Column('On_ART_10_14_F', Integer),
    Column('On_ART_15_19_M', Integer),
    Column('On_ART_15_19_F', Integer),
    Column('On_ART_20_24_M', Integer),
    Column('On_ART_20_24_F', Integer),
    Column('On_ART_25_Plus_M', Integer),
    Column('On_ART_25_Plus_F', Integer),
    Index('UniqueCheck', 'DHISOrgId', 'SiteCode', 'ReportMonth_Year', unique=True)
)


t_FACT_HTS_DHIS2 = Table(
    'FACT_HTS_DHIS2', metadata,
    Column('id', CHAR(36, 'SQL_Latin1_General_CP1_CI_AS'), nullable=False, unique=True),
    Column('DHISOrgId', Unicode(510), index=True),
    Column('SiteCode', Unicode(510), index=True),
    Column('FacilityName', Unicode(510), index=True),
    Column('County', Unicode(510), index=True),
    Column('SubCounty', Unicode(510), index=True),
    Column('Ward', Unicode(510), index=True),
    Column('ReportMonth_Year', Unicode(510), index=True),
    Column('Tested_Total', Integer),
    Column('Positive_Total', Integer),
    Column('createdAt', DATETIMEOFFSET, nullable=False),
    Column('updatedAt', DATETIMEOFFSET, nullable=False),
    Column('Tested_1_9', Integer),
    Column('Tested_10_14_M', Integer),
    Column('Tested_10_14_F', Integer),
    Column('Tested_15_19_M', Integer),
    Column('Tested_15_19_F', Integer),
    Column('Tested_20_24_M', Integer),
    Column('Tested_20_24_F', Integer),
    Column('Tested_25_Plus_M', Integer),
    Column('Tested_25_Plus_F', Integer),
    Column('Positive_1_9', Integer),
    Column('Positive_10_14_M', Integer),
    Column('Positive_10_14_F', Integer),
    Column('Positive_15_19_M', Integer),
    Column('Positive_15_19_F', Integer),
    Column('Positive_20_24_M', Integer),
    Column('Positive_20_24_F', Integer),
    Column('Positive_25_Plus_M', Integer),
    Column('Positive_25_Plus_F', Integer),
    Index('UniqueCheck', 'DHISOrgId', 'SiteCode', 'ReportMonth_Year', unique=True)
)


t_FACT_PMTCT_DHIS2 = Table(
    'FACT_PMTCT_DHIS2', metadata,
    Column('id', CHAR(36, 'SQL_Latin1_General_CP1_CI_AS'), nullable=False, unique=True),
    Column('DHISOrgId', Unicode(510), index=True),
    Column('SiteCode', Unicode(510), index=True),
    Column('FacilityName', Unicode(510), index=True),
    Column('County', Unicode(510), index=True),
    Column('SubCounty', Unicode(510), index=True),
    Column('Ward', Unicode(510), index=True),
    Column('ReportMonth_Year', Unicode(510), index=True),
    Column('firstAncVisits', Integer),
    Column('deliveryFromHivPosMothers', Integer),
    Column('knownPosAt1stAnc', Integer),
    Column('intialTestAtAnc', Integer),
    Column('initialTestAtL&D', Integer),
    Column('initialTestAtPnc<=6wks', Integer),
    Column('knownHivStatusTotal', Integer),
    Column('retestingPnc<=6wks', Integer),
    Column('testedPnc>6wksTo6mnts', Integer),
    Column('knowPosAt1stAnc', Integer),
    Column('posResultsAnc', Integer),
    Column('posResultsL&D', Integer),
    Column('posResultsPnc<=6wks', Integer),
    Column('posPnc>6wksTo6mnts', Integer),
    Column('totalPos', Integer),
    Column('onHAARTat1stAnc', Integer),
    Column('startHAARTanc', Integer),
    Column('startHAARTL&D', Integer),
    Column('startHAARTpnc<=6wks', Integer),
    Column('onMaternalHAARTtotal', Integer),
    Column('startHAARTPnc>6wksto6mnts', Integer),
    Column('onMaternalHAART12mnts', Integer),
    Column('newCohort12mths', Integer),
    Column('syphilisScreened1stanc', Integer),
    Column('syphilisScreenedPos', Integer),
    Column('syphilisTreated', Integer),
    Column('HIVposMordernFP6wks', Integer),
    Column('HIVposPncVisits6wks', Integer),
    Column('knownStatus1stContact', Integer),
    Column('initialTestANCMale', Integer),
    Column('initialTestPncMale', Integer),
    Column('initialTestL&DMale', Integer),
    Column('totalKnownStatusMale', Integer),
    Column('1stAncKPAdolescencts', Integer),
    Column('PosResultAdolescents', Integer),
    Column('StartedHAARTAdolescentsTotal', Integer),
    Column('knownExposureAtPenta1', Integer),
    Column('totalGivenPenta1', Integer),
    Column('infantARVProphylANC', Integer),
    Column('infantARVProphylL&D', Integer),
    Column('infantARVProphyl<8wksPNC', Integer),
    Column('totalARVProphyl', Integer),
    Column('HEICtxDdsStart<2mnts', Integer),
    Column('initialPCR<8wks', Integer),
    Column('initialPCR>8wksTo12mnts', Integer),
    Column('initialPCRtest<12mntsTotal', Integer),
    Column('infected24mnts', Integer),
    Column('uninfected24mnts', Integer),
    Column('unknownOutcome', Integer),
    Column('netCohortHEI24mnts', Integer),
    Column('motherBabyPairs24mnts', Integer),
    Column('pairNetCohort24mnts', Integer),
    Column('EBFat6mnts', Integer),
    Column('ERFat6mnts', Integer),
    Column('MFat6mnts', Integer),
    Column('BFat12mnts', Integer),
    Column('notBFat12mnts', Integer),
    Column('BFat18mnts', Integer),
    Column('notBFat18mnts', Integer),
    Column('createdAt', DATETIMEOFFSET, nullable=False),
    Column('updatedAt', DATETIMEOFFSET, nullable=False)
)
